[2025-07-07T07:35:06.697+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T07:33:57.814776+00:00 [queued]>
[2025-07-07T07:35:06.718+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T07:33:57.814776+00:00 [queued]>
[2025-07-07T07:35:06.723+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T07:35:06.753+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_dim_customer> on 2025-07-07 07:33:57.814776+00:00
[2025-07-07T07:35:06.762+0000] {standard_task_runner.py:57} INFO - Started process 566 to run task
[2025-07-07T07:35:06.767+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_dim_customer', 'manual__2025-07-07T07:33:57.814776+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmpxynnc4cf']
[2025-07-07T07:35:06.768+0000] {standard_task_runner.py:85} INFO - Job 213: Subtask trigger_dim_customer
[2025-07-07T07:35:07.023+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T07:33:57.814776+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T07:35:07.197+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_dim_customer' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T07:33:57.814776+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T07:33:57.814776+00:00'
[2025-07-07T07:35:07.281+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T07:35:07.281+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T07:35:07.198192+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T07:36:07.372+0000] {trigger_dagrun.py:210} INFO - etl_dim_customer finished with allowed state success
[2025-07-07T07:36:07.416+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=master_etl, task_id=trigger_dim_customer, execution_date=20250707T073357, start_date=20250707T073506, end_date=20250707T073607
[2025-07-07T07:36:07.519+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T07:36:07.728+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
