[2025-07-07T08:00:06.466+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_fact_claim manual__2025-07-07T07:44:54.258586+00:00 [queued]>
[2025-07-07T08:00:06.505+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_fact_claim manual__2025-07-07T07:44:54.258586+00:00 [queued]>
[2025-07-07T08:00:06.506+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T08:00:06.524+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_fact_claim> on 2025-07-07 07:44:54.258586+00:00
[2025-07-07T08:00:06.531+0000] {standard_task_runner.py:57} INFO - Started process 655 to run task
[2025-07-07T08:00:06.543+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_fact_claim', 'manual__2025-07-07T07:44:54.258586+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmpn7zz3jdb']
[2025-07-07T08:00:06.544+0000] {standard_task_runner.py:85} INFO - Job 249: Subtask trigger_fact_claim
[2025-07-07T08:00:06.614+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_fact_claim manual__2025-07-07T07:44:54.258586+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T08:00:06.688+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_fact_claim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T07:44:54.258586+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T07:44:54.258586+00:00'
[2025-07-07T08:00:06.760+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T08:00:06.760+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_fact_claim on 2025-07-07T08:00:06.689189+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T08:01:06.830+0000] {trigger_dagrun.py:210} INFO - etl_fact_claim finished with allowed state success
[2025-07-07T08:01:06.856+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=master_etl, task_id=trigger_fact_claim, execution_date=20250707T074454, start_date=20250707T080006, end_date=20250707T080106
[2025-07-07T08:01:06.919+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T08:01:07.072+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
