[2025-07-07T06:14:53.142+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T06:13:47.259414+00:00 [queued]>
[2025-07-07T06:14:53.155+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T06:13:47.259414+00:00 [queued]>
[2025-07-07T06:14:53.155+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-07T06:14:53.174+0000] {taskinstance.py:1327} INFO - Executing <Task(TriggerDagRunOperator): trigger_dim_customer> on 2025-07-07 06:13:47.259414+00:00
[2025-07-07T06:14:53.180+0000] {standard_task_runner.py:57} INFO - Started process 422 to run task
[2025-07-07T06:14:53.186+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'master_etl', 'trigger_dim_customer', 'manual__2025-07-07T06:13:47.259414+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/master_etl.py', '--cfg-path', '/tmp/tmpxhpfb5jc']
[2025-07-07T06:14:53.187+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask trigger_dim_customer
[2025-07-07T06:14:53.289+0000] {task_command.py:410} INFO - Running <TaskInstance: master_etl.trigger_dim_customer manual__2025-07-07T06:13:47.259414+00:00 [running]> on host 1622b3ff66d0
[2025-07-07T06:14:53.405+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='master_etl' AIRFLOW_CTX_TASK_ID='trigger_dim_customer' AIRFLOW_CTX_EXECUTION_DATE='2025-07-07T06:13:47.259414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-07T06:13:47.259414+00:00'
[2025-07-07T06:14:53.479+0000] {secrets_masker.py:278} WARNING - Unable to redact <TaskInstanceState.SUCCESS: 'success'>, please report this via <https://github.com/apache/airflow/issues>. Error was: TypeError: __call__() missing 1 required positional argument: 'value'
[2025-07-07T06:14:53.479+0000] {trigger_dagrun.py:201} INFO - Waiting for etl_dim_customer on 2025-07-07T06:14:53.406462+00:00 to become allowed state [<TaskInstanceState.SUCCESS: 'success'>] ...
[2025-07-07T06:15:53.512+0000] {trigger_dagrun.py:210} INFO - etl_dim_customer finished with allowed state success
[2025-07-07T06:15:53.527+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=master_etl, task_id=trigger_dim_customer, execution_date=20250707T061347, start_date=20250707T061453, end_date=20250707T061553
[2025-07-07T06:15:53.584+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-07-07T06:15:53.649+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
